/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2e.pertemuan3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INTEL
 */
public class MahasiswaView extends javax.swing.JPanel {

    /**
     * Creates new form MahasiswaView
     */
    public MahasiswaView() {
        initComponents();
        ulang();
        tampil_data();
    }
    Connection con = new Koneksi().getKoneksi();
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel dtm; //pilih add import apabila merah
 
    
    private void ulang(){
        buttonTambah.setEnabled(true);
        buttonUbah.setEnabled(false);
        buttonHapus.setEnabled(false);
        textNPM.setText("");
        textNama.setText("");
        textAlamat.setText("");
        jRadioTI.setSelected(true);
    }
    
    //method tampil data
    private void tampil_data(){
        try {
           String[] judul = {"ID", "NPM", "NAMA LENGKAP", "ALAMAT", "PRODI", "GOLDAR" };//untuk judul tabel
           dtm = new DefaultTableModel(null,judul);
           tabelMahasiswa.setModel(dtm);
           String sql = "";
           if(cari.getText().isEmpty()){
               sql = "select * from mahasiswa";
           }else{
               sql = "select * from mahasiswa where Nama_lengkap like '%" + cari.getText()+"%'";
           }
           pst = con.prepareStatement("select * from mahasiswa");//menjalankan query
           rs = pst.executeQuery();//karena query select, maka ambil data pakai rs
           while(rs.next()){ //lakukan perulangan selama datanya ada
               String[] data = {rs.getString(1), rs.getString(2),rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};//rs.getSrting[1] mengambil data di kolom yaitu ID.
               dtm.addRow(data);//data dimasukan ke dalam tabel
           }
               
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNPM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonUlang = new javax.swing.JButton();
        textTutup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        labelID = new javax.swing.JLabel();
        comboboxgoldar = new javax.swing.JComboBox<>();
        cari = new javax.swing.JTextField();
        jRadioTI = new javax.swing.JRadioButton();
        jRadioSI = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        panel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("FORM MAHASISWA");

        jLabel2.setText("NPM");

        jLabel3.setText("NAMA LENGKAP");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("PRODI");

        jLabel6.setText("GOLDAR");

        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setText("UBAH");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonUlang.setText("ULANG");
        buttonUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUlangActionPerformed(evt);
            }
        });

        textTutup.setText("TUTUP");
        textTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTutupActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data Mahasiswa Berdasarkan nama");

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        labelID.setText("jLabel8");

        comboboxgoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioTI);
        jRadioTI.setText("TEKNIK INFORMATIKA");

        buttonGroup1.add(jRadioSI);
        jRadioSI.setText("SISTEM INFORMASI");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAlamat)
                            .addComponent(textNama)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(textNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(labelID))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jRadioTI, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioSI, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboboxgoldar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cari)))
                .addGap(254, 254, 254))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(498, 498, 498)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID))
                        .addGap(26, 26, 26)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioTI)
                                    .addComponent(jRadioSI))))
                        .addGap(35, 35, 35)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboboxgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah)
                            .addComponent(buttonUbah)
                            .addComponent(buttonHapus)
                            .addComponent(buttonUlang))
                        .addGap(18, 18, 18)
                        .addComponent(textTutup))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        if(textNPM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NPM belum diinput");
            textNPM.requestFocus();
        }else if(textNama.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Nama belum diinput");
            textNama.requestFocus();
        }else if(textAlamat.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Alamat belum diinput");
            textAlamat.requestFocus();
        }else{
            try{
                String prodi = "TEKNIK INFORMATIKA";
                if(jRadioTI.isSelected()){
                    prodi = "SISTEM INFORMASI";

                }
                pst = con.prepareStatement("insert into mahasiswa values (?,?,?,?,?,?)");
                pst.setInt(1, 0);
                pst.setString(2, textNPM.getText());
                pst.setString(3, textNama.getText());
                pst.setString(4,textAlamat.getText());
                pst.setString(5, prodi);
                pst.setString(6,comboboxgoldar.getSelectedItem().toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data mahasiswa berhasil ditambahkan");
                ulang();
                tampil_data();
            }catch(Exception e){
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        if(textNPM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NPM belum diinput");
            textNPM.requestFocus();
        }else if(textNama.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Nama belum diinput");
            textNama.requestFocus();
        }else if(textAlamat.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Alamat belum diinput");
            textAlamat.requestFocus();
        }else{
            try{
                String prodi = "Teknik Informatika";
                if(jRadioTI.isSelected()){
                    prodi = "Sistem Informasi";

                }
                pst = con.prepareStatement("update mahasiswa set npm=?, nama_lengkap=?, alamat=?, prodi=?, goldar=? where id=?");
                pst.setInt(1, 0);
                pst.setString(1, textNPM.getText());
                pst.setString(2, textNama.getText());
                pst.setString(3,textAlamat.getText());
                pst.setString(4, prodi);
                pst.setString(5,comboboxgoldar.getSelectedItem().toString());
                pst.setInt(6, Integer.parseInt(labelID.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data mahasiswa berhasil diperbaharui");
                ulang();
                tampil_data();
            }catch(Exception e){
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(null, "yakin ingin menghapus data mahasiswa ini?", "HAPUS DATA?", 0);
        if(konfirmasi==0){
            try{
                pst = con.prepareStatement("delete from mahasiswa where id =?");
                pst.setInt(1, Integer.parseInt(labelID.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Mahasiswa berhasil dihapus!");
                ulang();
                tampil_data();
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUlangActionPerformed
        ulang();
    }//GEN-LAST:event_buttonUlangActionPerformed

    private void textTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTutupActionPerformed
        int index = HomeView.jTabbedPane1.getSelectedIndex();
        HomeView.jTabbedPane1.remove(index);
    }//GEN-LAST:event_textTutupActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        int row = tabelMahasiswa.getSelectedRow();
        labelID.setText(tabelMahasiswa.getValueAt(row, 0).toString());
        textNPM.setText(tabelMahasiswa.getValueAt(row, 1).toString());
        textNama.setText(tabelMahasiswa.getValueAt(row, 2).toString());
        textAlamat.setText(tabelMahasiswa.getValueAt(row, 3).toString());
        String prodi = tabelMahasiswa.getValueAt(row, 4).toString();
        comboboxgoldar.setSelectedItem(tabelMahasiswa.getValueAt(row, 5).toString());
        if(prodi.equalsIgnoreCase("Teknik Informatika")){
            jRadioTI.setSelected(true);
        }else{
            jRadioSI.setSelected(true);

        }

        buttonTambah.setEnabled(false);
        buttonUbah.setEnabled(true);
        buttonHapus.setEnabled(true);
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        tampil_data();   // TODO add your handling code here:
    }//GEN-LAST:event_cariKeyReleased

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
    tampil_data();   // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JButton buttonUlang;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> comboboxgoldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioSI;
    private javax.swing.JRadioButton jRadioTI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private java.awt.Panel panel1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textNPM;
    private javax.swing.JTextField textNama;
    private javax.swing.JButton textTutup;
    // End of variables declaration//GEN-END:variables
}
