/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2e.pertemuan3;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author INTEL
 */
public class PemilihanView extends javax.swing.JPanel {

    /**
     * Creates new form PemilihanView
     */
    public PemilihanView() {
        initComponents();
        tampil_tempat();//memanggil method tempat
        ulang();//panggil method ulang
    }
Connection con = new Koneksi().getKoneksi();
PreparedStatement pst;
ResultSet rs;
DefaultTableModel dtm;

private void get_id_pemilihan(){//menampilkan id pemilihan
        try {
            pst = con.prepareStatement("select * from pemilihan_tempat order by id_pemilihan desc limit 1");
            rs = pst.executeQuery();
            if(rs.next()){
                int id = rs.getInt(1) + 1;
                labelIDPemilihan.setText(id+"");
            }else{
                labelIDPemilihan.setText("1");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

private void tampil_tempat(){ //menampilkan data tempat pkl ke dalam combobox
        try {
            ComboTempat.addItem("Pilih Tempat PKL");
            pst = con.prepareStatement("select * from tempat_pkl");
            rs = pst.executeQuery();
            while(rs.next()){
                ComboTempat.addItem(rs.getString(2)); //memasukan nama tempat ke dalam combobox                       
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

private void ulang(){
    get_id_pemilihan();//memanggil method get id pemilihan
    TanggalMulai.setDate(null);
    TanggalSelesai.setDate(null);
    ComboTempat.setSelectedIndex(0);//mengatur index pada comboTempat
    TextAlamatPKL.setText("");
    LabelIDTempat.setText("");
    LabelIDMahasiswa.setText("");
    TextNPM.setText("");
    TextNama.setText("");
    TextAlamat.setText("");
    TextProdi.setText("");
        dtm = (DefaultTableModel)TableMahasiswa.getModel();
        dtm.setRowCount(0);
}
 private void simpan_pemilihan(){
     try{
         SimpleDateFormat formatTanggal = new SimpleDateFormat("yyy-MM-dd");
         pst = con.prepareStatement("insert into pemilihan_tempat values(?,?,?,?)");
         pst.setInt(1, 0);
         pst.setString(2, formatTanggal.format(TanggalMulai.getDate()));
         pst.setString(3, formatTanggal.format(TanggalSelesai.getDate()));
         pst.setString(4, LabelIDTempat.getText());
         pst.executeUpdate();
     }catch(SQLException e){
         System.out.println(e.getMessage());
     }
 }
 
private void simpan_detail_pemilihan(){
    try{
        int i = 0;
        while(i<TableMahasiswa.getRowCount()){
            pst = con.prepareStatement("insert into pemilihan_detail values(?,?,?)");
            pst.setInt(1, 0);
            pst.setString(2, labelIDPemilihan.getText());
            pst.setString(3, TableMahasiswa.getValueAt(i, 0).toString());
            pst.executeUpdate();
            i++;
        }
    }catch (Exception e){
        System.out.println(e.getMessage());
    }
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelIDPemilihan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboTempat = new javax.swing.JComboBox<>();
        LabelIDTempat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextAlamatPKL = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TextNPM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TextAlamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TextProdi = new javax.swing.JTextField();
        LabelIDMahasiswa = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMahasiswa = new javax.swing.JTable();
        ButtonHapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonSimpan = new javax.swing.JButton();
        ButtonUlang = new javax.swing.JButton();
        ButtonTutup = new javax.swing.JButton();
        TanggalMulai = new com.toedter.calendar.JDateChooser();
        TanggalSelesai = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM PEMILIHAN VIEW");

        jLabel2.setText("ID PEMILIHAN");

        labelIDPemilihan.setText("jLabel3");

        jLabel4.setText("TANGGA MULAI");

        jLabel5.setText("TANGGAL SELESAI");

        jLabel6.setText("NAMA TEMPAT PKL");

        ComboTempat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTempatItemStateChanged(evt);
            }
        });

        LabelIDTempat.setText("jLabel7");

        jLabel8.setText("ALAMAT PKL");

        TextAlamatPKL.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        jLabel9.setText("NPM MAHASISWA");

        TextNPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNPMKeyPressed(evt);
            }
        });

        jLabel10.setText("NAMA LENGKAP");

        TextNama.setEditable(false);

        jLabel11.setText("ALAMAT");

        TextAlamat.setEditable(false);

        jLabel12.setText("PRODI");

        TextProdi.setEditable(false);

        LabelIDMahasiswa.setText("jLabel13");

        ButtonTambah.setText("TAMBAH");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        TableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID MAHASISWA", "NPM", "NAMA LENGKAP", "ALAMAT", "PRODI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableMahasiswa);

        ButtonHapus.setText("HAPUS");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelIDMahasiswa))
                            .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextAlamat)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextProdi)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonHapus)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIDMahasiswa))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonTambah))))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonSimpan.setText("SIMPAN");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonUlang.setText("ULANG");
        ButtonUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUlangActionPerformed(evt);
            }
        });

        ButtonTutup.setText("TUTUP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(67, 67, 67)
                                        .addComponent(labelIDPemilihan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TanggalSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26)
                                        .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextAlamatPKL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(LabelIDTempat)
                                        .addGap(33, 33, 33)))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelIDPemilihan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(TanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ComboTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelIDTempat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TextAlamatPKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSimpan)
                        .addComponent(ButtonUlang)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
    if(TanggalMulai.getDate()==null){
        JOptionPane.showMessageDialog(null, "Tangaal mulai belum dipilih!", "Gagal simpan",0);
        TanggalMulai.requestFocus();
    }else if(TanggalSelesai.getDate()==null){
        JOptionPane.showMessageDialog(null, "Tanggal selesai belum dipilih!", "Gagal simpan",0);
        TanggalSelesai.requestFocus();
    }else if(LabelIDTempat.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Tempat PKL belum dipilih!", "Gagal simpan",0);
        ComboTempat.requestFocus();
    }else if(TableMahasiswa.getRowCount()<=0){
        JOptionPane.showMessageDialog(null, "Data Mahasiswa belum dipilih!", "Gagal simpan",0);
        ComboTempat.requestFocus();
    }else{
        simpan_pemilihan();
        simpan_detail_pemilihan();
        JOptionPane.showMessageDialog(null, "Data Pemilihan tempat PKL berhasil disimpan!", "Sukses simpan data", 1);
    }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUlangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUlangActionPerformed

    private void ComboTempatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTempatItemStateChanged
    try {
            String nama = ComboTempat.getSelectedItem().toString();
            pst = con.prepareStatement("select * from tempat_pkl where nama_tempat=?");
            pst.setString(1, nama);
            rs = pst.executeQuery();
            if(rs.next()){
                TextAlamatPKL.setText(rs.getString(3));
                LabelIDTempat.setText(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ComboTempatItemStateChanged

    private void TextNPMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNPMKeyPressed
    if(evt.getKeyChar() == 10){
            try {
                pst = con.prepareStatement("select * from mahasiswa where npm = ?");
                pst.setString(1, TextNPM.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    LabelIDMahasiswa.setText(rs.getString(1));
                    TextNama.setText(rs.getString(3));
                    TextAlamat.setText(rs.getString(4));
                    TextProdi.setText(rs.getString(5));                                        
                }else{
                    JOptionPane.showMessageDialog(null, "NPM tidak ditemukan!", "Not Found", 0);
                    TextNPM.requestFocus();
                    TextNPM.setText("");
                }                    
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_TextNPMKeyPressed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
    if(LabelIDMahasiswa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data mahasiswa belum diinput!", "Gagal Tambah", 0);
        }else{
            String[] data ={LabelIDMahasiswa.getText(), TextNPM.getText(), TextNama.getText(), TextAlamat.getText(), TextProdi.getText()};
            dtm.addRow(data);//memasukan data ke dalam tabel
            LabelIDMahasiswa.setText("");
            TextNPM.setText("");
            TextNama.setText("");
            TextAlamat.setText("");
            TextProdi.setText("");
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
    int baris = TableMahasiswa.getSelectedRow();
        if(baris<0){
            JOptionPane.showMessageDialog(null, "Data mahasiswa yang ingin dihapus belum dipilih",
                    "Pilih Data Dulu!", 0);
        }else{
            dtm.removeRow(baris);
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton ButtonTutup;
    private javax.swing.JButton ButtonUlang;
    private javax.swing.JComboBox<String> ComboTempat;
    private javax.swing.JLabel LabelIDMahasiswa;
    private javax.swing.JLabel LabelIDTempat;
    private javax.swing.JTable TableMahasiswa;
    private com.toedter.calendar.JDateChooser TanggalMulai;
    private com.toedter.calendar.JDateChooser TanggalSelesai;
    private javax.swing.JTextField TextAlamat;
    private javax.swing.JTextField TextAlamatPKL;
    private javax.swing.JTextField TextNPM;
    private javax.swing.JTextField TextNama;
    private javax.swing.JTextField TextProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelIDPemilihan;
    // End of variables declaration//GEN-END:variables

}
